const CONFIG = {
  PORT: process.env.PORT || 3000,
  SESSION_INACTIVITY_TTL_MS: 10 * 60 * 1000, // 10 minutes
  LOCATION_STALE_MS: 30 * 1000, // 30 seconds
  REROUTE_DISTANCE_METERS: 100,
  REROUTE_ETA_DELTA_SECONDS: 120, // 2 minutes
  REROUTE_MIN_INTERVAL_MS: 30 * 1000, // 30 seconds
  REROUTE_MAX_PER_MINUTE: 2,
  REROUTE_HYSTERESIS_WINDOW_MS: 2 * 60 * 1000, // 2 minutes
  REROUTE_HYSTERESIS_MULTIPLIER: 1.5,
  JITTER_RADIUS_METERS: 30,
  THROTTLE_SPEED_MPS: {
    STATIONARY_MAX: 0.5,
    WALKING_MAX: 2.5,
  },
  THROTTLE_ACCURACY_METERS: {
    GOOD_MAX: 20,
    MEDIUM_MAX: 50,
  },
  THROTTLE_INTERVAL_SECONDS: {
    STATIONARY: 20,
    WALKING: 10,
    DRIVING: 5,
  },
  THROTTLE_ACCURACY_MULTIPLIER: {
    GOOD: 1,
    MEDIUM: 1.2,
    POOR: 1.6,
  },
};

module.exports = { CONFIG };
